# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import enumerify.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('type', enumerify.fields.SelectIntegerField(choices=[(0, b'-'), (1, b'Cash'), (2, b'Bank'), (3, b'IOU')], db_index=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'accounts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='accounts',
            unique_together=set([('label',)]),
        ),
    ]
